GET http://localhost:5000/users

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Capstone",
    "email": "capt@gmail.com",
    "password": "1234",
    "confpassword": "1234"

}